### ISSUE TITLE
Failed to find provider info for 

### ISSUE THREAD

**Issue by GabrielKuka** [Mauker1/MaterialSearchView#105]
I am trying to implement the searchview in my application. And everything is set up. When I try to run it, the app crashes saying: Failed to find provider info for....

`07-19 21:52:48.896 5494-5494/com.katana.memo.memo E/ActivityThread: Failed to find provider info for com.katana.memo.searchhistorydatabase
07-19 21:52:48.896 5494-5494/com.katana.memo.memo D/AndroidRuntime: Shutting down VM
07-19 21:52:48.897 5494-5494/com.katana.memo.memo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.katana.memo.memo, PID: 5494
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.katana.memo.memo/com.katana.memo.memo.Activities.Homepage}: java.lang.IllegalArgumentException: Unknown URL content://com.katana.memo.searchhistorydatabase/history
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                        at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                     Caused by: java.lang.IllegalArgumentException: Unknown URL content://com.katana.memo.searchhistorydatabase/history
                                                                        at android.content.ContentResolver.delete(ContentResolver.java:1373)
                                                                        at br.com.mauker.materialsearchview.MaterialSearchView.clearSuggestions(MaterialSearchView.java:1125)
                                                                        at com.katana.memo.memo.Activities.Homepage.setUpViews(Homepage.kt:135)
                                                                        at com.katana.memo.memo.Activities.Homepage.setUpActivity(Homepage.kt:110)
                                                                        at com.katana.memo.memo.Activities.Homepage.onCreate(Homepage.kt:64)
                                                                        at android.app.Activity.performCreate(Activity.java:6942)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                        at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
`

What can I do?

**Comment by Mauker1** [comment]
This looks like a setup problem.  It could either be a problem in the manifest or on the `MsvAuthority.java`.

Manifest
---
- Check if your `<provider>` tag is inside the <application> tag.
- Check the value of your `android:authorities` field.

MsvAuthority.java
---
- Check if the field `CONTENT_AUTHORITY` equals to what you defined on the manifest `android:authorities`, inside the `<provider>` tag.

**Comment by GabrielKuka** [comment]
What do you mean by: Check if your provideer taf is inside the tag? I don't understand.

**Comment by GabrielKuka** [comment]
Never mind. The provider tag was outside the application tag. So foolish of me. Thank you for your response sir.

**Comment by Mauker1** [comment]
Ops, I forgot to type `<application>` haha. And you're welcome!
