### ISSUE TITLE
SearchView filtered items do not reappear on backspace

### ISSUE THREAD

**Issue by karuhanga** [Mauker1/MaterialSearchView#147]
## Update
After a little more tinkering, It turns out the first part of the issue was coming from me checking if the the `newText` in when `onQueryChanged` is triggered is empty and not performing that search. Removing this **solved Issue 1**. This seems quite arbitrary though.

**The second issue still persists.**

**Issue 1**
Awesome tool.
I'm not sure what I'm doing wrong or if this is a bug.
The first time the `SearchView` is opened, the search methods properly trigger and results are properly presented when I call `searchView.addSuggestions(suggestions)`. The issue however is with every subsequent search, the first results to be presented are those from the previous search, regardless of the query that is typed.

**Issue 2**
After items have been filtered by the search, for  example when searching for `search`, when one gets to `sea`, hitting backspace, which should presumably trigger the search for and re-display the suggestions for `se` properly triggers the search, but keeps the suggestions for `sea` on the screen, even after calling `searchView.clearSuggestions()` and then `searchView.addSuggestions(suggestions)` until the search box is completely cleared and the search restarted.

I have turned off history via `searchView.setShouldKeepHistory(false);`

**Comment by Mauker1** [comment]
Hello! Thanks for your input!

As for issue 1, this is the default behavior. MSV will show the search history first, and that can be turned off with the method you used (`searchView.setShouldKeepHistory(false);`).

Now, about issue 2, could you make a gif of that?

**Comment by Karuhanga** [comment]
It seems to work sometimes and not other times.

![1](https://user-images.githubusercontent.com/12200860/50664229-676dde80-0fbd-11e9-8bd3-42bb8616c8ba.gif)
![2](https://user-images.githubusercontent.com/12200860/50664247-748acd80-0fbd-11e9-8f1d-20d89ad30d0a.gif)

**Comment by fengqiyun** [comment]
hello,Mauker1.I'm sorry to come down to your homepage and ask such a question。I'm replicating segan's experiment, the paper is SEGAN:SEGAN: Speech Enhancement Generative Adversarial Network, I saw your message on the github page of Santiago,I know that you have successfully reproduced all the experiments of the article and completed the test.I have a problem loading the trained model for testing, it may be my clean_wav.sh script modification has a problem, so I would like to consult you。
The system reported an error as follows:
Not clipping D weights
Loading model weights...
[*] Reading checkpoints...
[*] Read SEGAN-41700
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    tf.app.run()
  File "/home/zyf/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 102, in main
    fm, wav_data = wavfile.read(FLAGS.test_wav)
  File "/home/zyf/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
IOError: [Errno 21] Is a directory: '/home/zyf/SEGAN/segan-master1/test_wav/noisy_testset_wav'
I am very eager to finish the test part of the experiment, and I hope you can help me. My name is zhou yao feng, my e-mail is zhouyaofeng@hotmail.com,If possible, we can contact by email.
Thank you.
