### ISSUE TITLE
Cannot start this animator on a detached view

### ISSUE THREAD

**Issue by dav1d337** [Mauker1/MaterialSearchView#158]
After calling openSearch() i get the following error:

    java.lang.IllegalStateException: Cannot start this animator on a detached view!
        at android.view.RenderNode.addAnimator(RenderNode.java:824)
        at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:295)
        at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:280)
        at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
        at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
        at br.com.mauker.materialsearchview.utils.AnimationUtils.circleRevealView(AnimationUtils.java:34)
        at br.com.mauker.materialsearchview.utils.AnimationUtils.circleRevealView(AnimationUtils.java:50)
        at br.com.mauker.materialsearchview.MaterialSearchView.openSearch(MaterialSearchView.java:520)

Any one has a hint for me?

**Comment by dav1d337** [comment]
Okay, i when i move the openSearch() into onCreateView() with the following code it works

        rootView = inflater.inflate(R.layout.kiosk_fragment, container, false)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            rootView?.addOnLayoutChangeListener(object : View.OnLayoutChangeListener {
                @TargetApi(Build.VERSION_CODES.LOLLIPOP)
                override fun onLayoutChange(v: View, left: Int, top: Int, right: Int, bottom: Int, oldLeft: Int, oldTop: Int, oldRight: Int, oldBottom: Int) {
                    v.removeOnLayoutChangeListener(this)
                    searchView.openSearch()
                }
            })
        }
