### ISSUE TITLE
 Unknown URL content

### ISSUE THREAD

**Issue by lvtanxi** [Mauker1/MaterialSearchView#42]
`java.lang.IllegalArgumentException: Unknown URL content://br.com.mauker.materialsearchview.defaultsearchhistorydatabase/history
                                                               at android.content.ContentResolver.insert(ContentResolver.java:1233)
                                                               at br.com.mauker.materialsearchview.MaterialSearchView.saveQueryToDb(MaterialSearchView.java:857)
                                                               at br.com.mauker.materialsearchview.MaterialSearchView.onSubmitQuery(MaterialSearchView.java:626)
                                                               at br.com.mauker.materialsearchview.MaterialSearchView.access$400(MaterialSearchView.java:52)
                                                               at br.com.mauker.materialsearchview.MaterialSearchView$6.onEditorAction(MaterialSearchView.java:362)
                                                               at android.widget.TextView.onEditorAction(TextView.java:4490)
                                                               at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
                                                               at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
                                                               at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:135)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)`

**Comment by Mauker1** [comment]
You forgot to add your own custom provider authority. As from the README, you need to do the following:

## Setup

Before you can use this lib, you have to implement a class named `MsvAuthority` inside the `br.com.mauker` package on your app module, and it should have a public static String variable called `CONTENT_AUTHORITY`. Give it the value you want and **don't forget** to add the same name on your manifest file. The lib will use this file to set the Content Provider authority.

**Example:**

**MsvAuthority.java**

```java
package br.com.mauker;

public class MsvAuthority {
    public static final String CONTENT_AUTHORITY = "br.com.mauker.materialsearchview.searchhistorydatabase";
}
```

**AndroidManifest.xml**

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>

    <application ... >
        <provider
        android:name="br.com.mauker.materialsearchview.db.HistoryProvider"
        android:authorities="br.com.mauker.materialsearchview.searchhistorydatabase"
        android:exported="false"
        android:protectionLevel="signature"
        android:syncable="true"/>
    </application>

</manifest>
```

**Comment by lvtanxi** [comment]
`public class MsvAuthority {
    public static final String CONTENT_AUTHORITY = "br.com.mauker.materialsearchview.searchhistorydatabase";
}`
MsvAuthority path is written death, in the code to use reflection to obtain, can open a method of dynamic set CONTENT_AUTHORITY, or CONTENT_AUTHORITY is set in the lib?

**Comment by Mauker1** [comment]
You can change the `CONTENT_AUTHORITY` String as you will. I recommend using your own unique URI for that. Just as you do with your app id, with your reverse domain. 

**E.g.:** `com.yourdomain.myapp.myproviderdatabase`

And this String should be the same as the one on the `<provider>` tag on your manifest. 

**E.g.:**

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>

    <application ... >
        <provider
        android:name="com.yourdomain.myapp.myprovider"
        android:authorities="com.yourdomain.myapp.myproviderdatabase"
        android:exported="false"
        android:protectionLevel="signature"
        android:syncable="true"/>
    </application>

</manifest>
```

**Comment by Mauker1** [comment]
@lvtanxi Any news?

**Comment by Mauker1** [comment]
Closing this issue as OP stopped responding and it seems to be just a configuration problem.

**Comment by lvtanxi** [comment]
I've solved, thank you

**Comment by rajeevjaiswal** [comment]
How to create own custom provider authority?
