### ISSUE TITLE
java.lang.NoSuchFieldError: No static field iv_icon of type I in class Lbr/com/mauker/materialsearchview

### ISSUE THREAD

**Issue by Rajan** [Mauker1/MaterialSearchView#49]
It crashes when an actual suggestion is found.

`09-28 21:45:22.760 22743-22743/com.skillchat E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.skillchat, PID: 22743
                                                               java.lang.NoSuchFieldError: No static field iv_icon of type I in class Lbr/com/mauker/materialsearchview/R$id; or its superclasses (declaration of 'br.com.mauker.materialsearchview.R$id' appears in /data/data/com.skillchat/files/instant-run/dex/slice-slice_8-classes.dex)
                                                                   at br.com.mauker.materialsearchview.adapters.CursorSearchAdapter$ListViewHolder.<init>(CursorSearchAdapter.java:69)
                                                                   at br.com.mauker.materialsearchview.adapters.CursorSearchAdapter.bindView(CursorSearchAdapter.java:33)
                                                                   at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
                                                                   at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                   at android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
                                                                   at android.widget.ListView.onMeasure(ListView.java:1188)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:706)
                                                                   at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:773)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:706)
                                                                   at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:773)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1085)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                               	at android.os.Handler.dispatchMessage(Han
09-28 21:45:22.762 800-10090/system_process W/ActivityManager:   Force finishing activity com.skillchat/.MainActivity
                                                               
                                                               [ 09-28 21:45:22.767   800:10090 D/         ]
                                                               HostConnection::get() New Host Connection established 0xdca730b0, tid 10090
09-28 21:45:22.777 813-813/? E/EGL_emulation: tid 813: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)`

**Comment by Rajan** [comment]
I had another file named list_item and that resulted in the conflict.
Refactored (renamed) it and it's working now.
