### ISSUE TITLE
Force closes the app when running Lollipop

### ISSUE THREAD

**Issue by ErickVrech** [Mauker1/MaterialSearchView#94]
Apparently I have a problem similar to #92 , I made the setup with version 1.2.2 and I followed all the above comments but the error persists, closing an application to try to inflate the layout, follow the detailed error below:

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.searchbartest, PID: 11698
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.searchbartest/com.searchbartest.MainActivity}: android.view.InflateException: Binary XML file line #15: Error inflating class br.com.mauker.materialsearchview.MaterialSearchView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                      at android.app.ActivityThread.access$800(ActivityThread.java:155)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                   Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class br.com.mauker.materialsearchview.MaterialSearchView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at com.searchbartest.MainActivity.onCreate(MainActivity.java:17)
                      at android.app.Activity.performCreate(Activity.java:6010)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5343) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at com.searchbartest.MainActivity.onCreate(MainActivity.java:17) 
                      at android.app.Activity.performCreate(Activity.java:6010) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5343) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
                   Caused by: java.lang.NoSuchFieldError: No static field search_layout of type I in class Lbr/com/mauker/materialsearchview/R$id; or its superclasses (declaration of 'br.com.mauker.materialsearchview.R$id' appears in /data/data/com.searchbartest/files/instant-run/dex/slice-slice_8-classes.dex)
                      at br.com.mauker.materialsearchview.MaterialSearchView.init(MaterialSearchView.java:225)
                      at br.com.mauker.materialsearchview.MaterialSearchView.<init>(MaterialSearchView.java:209)
                      at br.com.mauker.materialsearchview.MaterialSearchView.<init>(MaterialSearchView.java:197)
                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:802) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at com.searchbartest.MainActivity.onCreate(MainActivity.java:17) 
                      at android.app.Activity.performCreate(Activity.java:6010) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:155) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5343) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) `

Follow the code for the Gradle:

`
 apply plugin: "com.android.application"

 android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    dexOptions {
        javaMaxHeapSize "2g"
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }

    sourceSets {
        main.jniLibs.srcDirs = ['libs']
        test.jniLibs.srcDirs = ['libs']
    }

    defaultConfig {
        applicationId "com.searchbartest
        multiDexEnabled true
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 12
        versionName "2.4"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: [
            '*.jar])
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support:support-v4:25.2.0'
    compile 'com.android.support:cardview-v7:25.2.0'
    compile 'me.dm7.barcodescanner:zxing:1.8.4'
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.github.paolorotolo:appintro:4.1.0'
    compile 'br.com.mauker.materialsearchview:materialsearchview:1.2.2'
    compile 'com.google.firebase:firebase-core:10.2.0'
    compile 'com.google.firebase:firebase-messaging:10.2.0'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.android.support:recyclerview-v7:25.2.0'
    testCompile 'junit:junit:4.12'
}
`

**Comment by ErickVrech** [comment]
Resolved, in my app I had a layout called 'search_view.xml', which generated conflict in the initialization of the MaterialSearchView class because internally it also has a layout called 'search_view', which resulted in a conflict of my design with that of Mauker.

Thank you and great work mauker

**Comment by Mauker1** [comment]
You're welcome! I got here a little late, but I'm glad you sorted it out. Thanks!
